// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RACS2Bridge_geometry_msgs.proto

#include "RACS2Bridge_geometry_msgs.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_RACS2Bridge_5fgeometry_5fmsgs_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto;
class RACS2Bridge_geometry_msgs_Vector3DefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RACS2Bridge_geometry_msgs_Vector3> _instance;
} _RACS2Bridge_geometry_msgs_Vector3_default_instance_;
class RACS2Bridge_geometry_msgs_TwistDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RACS2Bridge_geometry_msgs_Twist> _instance;
} _RACS2Bridge_geometry_msgs_Twist_default_instance_;
class RACS2Bridge_geometry_msgsDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<RACS2Bridge_geometry_msgs> _instance;
} _RACS2Bridge_geometry_msgs_default_instance_;
static void InitDefaultsscc_info_RACS2Bridge_geometry_msgs_RACS2Bridge_5fgeometry_5fmsgs_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RACS2Bridge_geometry_msgs_default_instance_;
    new (ptr) ::RACS2Bridge_geometry_msgs();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RACS2Bridge_geometry_msgs::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RACS2Bridge_geometry_msgs_RACS2Bridge_5fgeometry_5fmsgs_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RACS2Bridge_geometry_msgs_RACS2Bridge_5fgeometry_5fmsgs_2eproto}, {}};

static void InitDefaultsscc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RACS2Bridge_geometry_msgs_Twist_default_instance_;
    new (ptr) ::RACS2Bridge_geometry_msgs_Twist();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RACS2Bridge_geometry_msgs_Twist::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto}, {
      &scc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base,}};

static void InitDefaultsscc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RACS2Bridge_geometry_msgs_Vector3_default_instance_;
    new (ptr) ::RACS2Bridge_geometry_msgs_Vector3();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RACS2Bridge_geometry_msgs_Vector3::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_RACS2Bridge_5fgeometry_5fmsgs_2eproto[3];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_RACS2Bridge_5fgeometry_5fmsgs_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_RACS2Bridge_5fgeometry_5fmsgs_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_RACS2Bridge_5fgeometry_5fmsgs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Vector3, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Vector3, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Vector3, x_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Vector3, y_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Vector3, z_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Twist, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Twist, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Twist, linear_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs_Twist, angular_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, accel_with_covariance_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, accel_with_covariance_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, point_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, inertia_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, quaternion_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, transform_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, inertia_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_with_covariance_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, twist_covariance_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, wrench_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, accel_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_with_covariance_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, accele_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, transform_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, point_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, polygon_stamped_dta_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_array_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, vector3_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, polygon_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, queaternion_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, point32_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, twist_with_covariance_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, twist_stamped_data_),
  PROTOBUF_FIELD_OFFSET(::RACS2Bridge_geometry_msgs, pose_2d_data_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 8, sizeof(::RACS2Bridge_geometry_msgs_Vector3)},
  { 11, 18, sizeof(::RACS2Bridge_geometry_msgs_Twist)},
  { 20, -1, sizeof(::RACS2Bridge_geometry_msgs)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_RACS2Bridge_geometry_msgs_Vector3_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_RACS2Bridge_geometry_msgs_Twist_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_RACS2Bridge_geometry_msgs_default_instance_),
};

const char descriptor_table_protodef_RACS2Bridge_5fgeometry_5fmsgs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\037RACS2Bridge_geometry_msgs.proto\"D\n!RAC"
  "S2Bridge_geometry_msgs_Vector3\022\t\n\001x\030\001 \002("
  "\001\022\t\n\001y\030\002 \002(\001\022\t\n\001z\030\003 \002(\001\"\212\001\n\037RACS2Bridge_"
  "geometry_msgs_Twist\0222\n\006linear\030\001 \002(\0132\".RA"
  "CS2Bridge_geometry_msgs_Vector3\0223\n\007angul"
  "ar\030\002 \002(\0132\".RACS2Bridge_geometry_msgs_Vec"
  "tor3\"\351\006\n\031RACS2Bridge_geometry_msgs\022&\n\032ac"
  "cel_with_covariance_data\030\001 \003(\002B\002\020\001\022.\n\"ac"
  "cel_with_covariance_stamped_data\030\002 \003(\002B\002"
  "\020\001\022\036\n\022point_stamped_data\030\003 \003(\002B\002\020\001\022 \n\024in"
  "ertia_stamped_data\030\004 \003(\002B\002\020\001\022#\n\027quaterni"
  "on_stamped_data\030\005 \003(\002B\002\020\001\022\"\n\026transform_s"
  "tamped_data\030\006 \003(\002B\002\020\001\022\030\n\014inertia_data\030\007 "
  "\003(\002B\002\020\001\022%\n\031pose_with_covariance_data\030\010 \003"
  "(\002B\002\020\001\022)\n\035twist_covariance_stamped_data\030"
  "\t \003(\002B\002\020\001\022\027\n\013wrench_data\030\n \003(\002B\002\020\001\022\026\n\nac"
  "cel_data\030\013 \003(\002B\002\020\001\022-\n!pose_with_covarian"
  "ce_stamped_data\030\014 \003(\002B\002\020\001\022\037\n\023accele_stam"
  "ped_data\030\r \003(\002B\002\020\001\022\032\n\016transform_data\030\016 \003"
  "(\002B\002\020\001\022\026\n\npoint_data\030\017 \003(\002B\002\020\001\022\037\n\023polygo"
  "n_stamped_dta\030\020 \003(\002B\002\020\001\022\033\n\017pose_array_da"
  "ta\030\021 \003(\002B\002\020\001\022 \n\024vector3_stamped_data\030\022 \003"
  "(\002B\002\020\001\022\035\n\021pose_stamped_data\030\023 \003(\002B\002\020\001\022\030\n"
  "\014polygon_data\030\024 \003(\002B\002\020\001\022\034\n\020queaternion_d"
  "ata\030\025 \003(\002B\002\020\001\022\030\n\014point32_data\030\026 \003(\002B\002\020\001\022"
  "&\n\032twist_with_covariance_data\030\027 \003(\002B\002\020\001\022"
  "\025\n\tpose_data\030\030 \003(\002B\002\020\001\022\036\n\022twist_stamped_"
  "data\030\031 \003(\002B\002\020\001\022\030\n\014pose_2d_data\030\032 \003(\002B\002\020\001"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_sccs[3] = {
  &scc_info_RACS2Bridge_geometry_msgs_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base,
  &scc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base,
  &scc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto = {
  false, false, descriptor_table_protodef_RACS2Bridge_5fgeometry_5fmsgs_2eproto, "RACS2Bridge_geometry_msgs.proto", 1120,
  &descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_once, descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_sccs, descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto_deps, 3, 0,
  schemas, file_default_instances, TableStruct_RACS2Bridge_5fgeometry_5fmsgs_2eproto::offsets,
  file_level_metadata_RACS2Bridge_5fgeometry_5fmsgs_2eproto, 3, file_level_enum_descriptors_RACS2Bridge_5fgeometry_5fmsgs_2eproto, file_level_service_descriptors_RACS2Bridge_5fgeometry_5fmsgs_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_RACS2Bridge_5fgeometry_5fmsgs_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_RACS2Bridge_5fgeometry_5fmsgs_2eproto)), true);

// ===================================================================

void RACS2Bridge_geometry_msgs_Vector3::InitAsDefaultInstance() {
}
class RACS2Bridge_geometry_msgs_Vector3::_Internal {
 public:
  using HasBits = decltype(std::declval<RACS2Bridge_geometry_msgs_Vector3>()._has_bits_);
  static void set_has_x(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_y(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_z(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

RACS2Bridge_geometry_msgs_Vector3::RACS2Bridge_geometry_msgs_Vector3(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:RACS2Bridge_geometry_msgs_Vector3)
}
RACS2Bridge_geometry_msgs_Vector3::RACS2Bridge_geometry_msgs_Vector3(const RACS2Bridge_geometry_msgs_Vector3& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&z_) -
    reinterpret_cast<char*>(&x_)) + sizeof(z_));
  // @@protoc_insertion_point(copy_constructor:RACS2Bridge_geometry_msgs_Vector3)
}

void RACS2Bridge_geometry_msgs_Vector3::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&z_) -
      reinterpret_cast<char*>(&x_)) + sizeof(z_));
}

RACS2Bridge_geometry_msgs_Vector3::~RACS2Bridge_geometry_msgs_Vector3() {
  // @@protoc_insertion_point(destructor:RACS2Bridge_geometry_msgs_Vector3)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RACS2Bridge_geometry_msgs_Vector3::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RACS2Bridge_geometry_msgs_Vector3::ArenaDtor(void* object) {
  RACS2Bridge_geometry_msgs_Vector3* _this = reinterpret_cast< RACS2Bridge_geometry_msgs_Vector3* >(object);
  (void)_this;
}
void RACS2Bridge_geometry_msgs_Vector3::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RACS2Bridge_geometry_msgs_Vector3::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RACS2Bridge_geometry_msgs_Vector3& RACS2Bridge_geometry_msgs_Vector3::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RACS2Bridge_geometry_msgs_Vector3_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base);
  return *internal_default_instance();
}


void RACS2Bridge_geometry_msgs_Vector3::Clear() {
// @@protoc_insertion_point(message_clear_start:RACS2Bridge_geometry_msgs_Vector3)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&x_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&z_) -
        reinterpret_cast<char*>(&x_)) + sizeof(z_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RACS2Bridge_geometry_msgs_Vector3::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required double x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 9)) {
          _Internal::set_has_x(&has_bits);
          x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // required double y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17)) {
          _Internal::set_has_y(&has_bits);
          y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // required double z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 25)) {
          _Internal::set_has_z(&has_bits);
          z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RACS2Bridge_geometry_msgs_Vector3::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RACS2Bridge_geometry_msgs_Vector3)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double x = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_x(), target);
  }

  // required double y = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_y(), target);
  }

  // required double z = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RACS2Bridge_geometry_msgs_Vector3)
  return target;
}

size_t RACS2Bridge_geometry_msgs_Vector3::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:RACS2Bridge_geometry_msgs_Vector3)
  size_t total_size = 0;

  if (_internal_has_x()) {
    // required double x = 1;
    total_size += 1 + 8;
  }

  if (_internal_has_y()) {
    // required double y = 2;
    total_size += 1 + 8;
  }

  if (_internal_has_z()) {
    // required double z = 3;
    total_size += 1 + 8;
  }

  return total_size;
}
size_t RACS2Bridge_geometry_msgs_Vector3::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RACS2Bridge_geometry_msgs_Vector3)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required double x = 1;
    total_size += 1 + 8;

    // required double y = 2;
    total_size += 1 + 8;

    // required double z = 3;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RACS2Bridge_geometry_msgs_Vector3::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RACS2Bridge_geometry_msgs_Vector3)
  GOOGLE_DCHECK_NE(&from, this);
  const RACS2Bridge_geometry_msgs_Vector3* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RACS2Bridge_geometry_msgs_Vector3>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RACS2Bridge_geometry_msgs_Vector3)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RACS2Bridge_geometry_msgs_Vector3)
    MergeFrom(*source);
  }
}

void RACS2Bridge_geometry_msgs_Vector3::MergeFrom(const RACS2Bridge_geometry_msgs_Vector3& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RACS2Bridge_geometry_msgs_Vector3)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      x_ = from.x_;
    }
    if (cached_has_bits & 0x00000002u) {
      y_ = from.y_;
    }
    if (cached_has_bits & 0x00000004u) {
      z_ = from.z_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void RACS2Bridge_geometry_msgs_Vector3::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RACS2Bridge_geometry_msgs_Vector3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RACS2Bridge_geometry_msgs_Vector3::CopyFrom(const RACS2Bridge_geometry_msgs_Vector3& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RACS2Bridge_geometry_msgs_Vector3)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RACS2Bridge_geometry_msgs_Vector3::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void RACS2Bridge_geometry_msgs_Vector3::InternalSwap(RACS2Bridge_geometry_msgs_Vector3* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RACS2Bridge_geometry_msgs_Vector3, z_)
      + sizeof(RACS2Bridge_geometry_msgs_Vector3::z_)
      - PROTOBUF_FIELD_OFFSET(RACS2Bridge_geometry_msgs_Vector3, x_)>(
          reinterpret_cast<char*>(&x_),
          reinterpret_cast<char*>(&other->x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RACS2Bridge_geometry_msgs_Vector3::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RACS2Bridge_geometry_msgs_Twist::InitAsDefaultInstance() {
  ::_RACS2Bridge_geometry_msgs_Twist_default_instance_._instance.get_mutable()->linear_ = const_cast< ::RACS2Bridge_geometry_msgs_Vector3*>(
      ::RACS2Bridge_geometry_msgs_Vector3::internal_default_instance());
  ::_RACS2Bridge_geometry_msgs_Twist_default_instance_._instance.get_mutable()->angular_ = const_cast< ::RACS2Bridge_geometry_msgs_Vector3*>(
      ::RACS2Bridge_geometry_msgs_Vector3::internal_default_instance());
}
class RACS2Bridge_geometry_msgs_Twist::_Internal {
 public:
  using HasBits = decltype(std::declval<RACS2Bridge_geometry_msgs_Twist>()._has_bits_);
  static const ::RACS2Bridge_geometry_msgs_Vector3& linear(const RACS2Bridge_geometry_msgs_Twist* msg);
  static void set_has_linear(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static const ::RACS2Bridge_geometry_msgs_Vector3& angular(const RACS2Bridge_geometry_msgs_Twist* msg);
  static void set_has_angular(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000003) ^ 0x00000003) != 0;
  }
};

const ::RACS2Bridge_geometry_msgs_Vector3&
RACS2Bridge_geometry_msgs_Twist::_Internal::linear(const RACS2Bridge_geometry_msgs_Twist* msg) {
  return *msg->linear_;
}
const ::RACS2Bridge_geometry_msgs_Vector3&
RACS2Bridge_geometry_msgs_Twist::_Internal::angular(const RACS2Bridge_geometry_msgs_Twist* msg) {
  return *msg->angular_;
}
RACS2Bridge_geometry_msgs_Twist::RACS2Bridge_geometry_msgs_Twist(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:RACS2Bridge_geometry_msgs_Twist)
}
RACS2Bridge_geometry_msgs_Twist::RACS2Bridge_geometry_msgs_Twist(const RACS2Bridge_geometry_msgs_Twist& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_linear()) {
    linear_ = new ::RACS2Bridge_geometry_msgs_Vector3(*from.linear_);
  } else {
    linear_ = nullptr;
  }
  if (from._internal_has_angular()) {
    angular_ = new ::RACS2Bridge_geometry_msgs_Vector3(*from.angular_);
  } else {
    angular_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:RACS2Bridge_geometry_msgs_Twist)
}

void RACS2Bridge_geometry_msgs_Twist::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base);
  ::memset(&linear_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&angular_) -
      reinterpret_cast<char*>(&linear_)) + sizeof(angular_));
}

RACS2Bridge_geometry_msgs_Twist::~RACS2Bridge_geometry_msgs_Twist() {
  // @@protoc_insertion_point(destructor:RACS2Bridge_geometry_msgs_Twist)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RACS2Bridge_geometry_msgs_Twist::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete linear_;
  if (this != internal_default_instance()) delete angular_;
}

void RACS2Bridge_geometry_msgs_Twist::ArenaDtor(void* object) {
  RACS2Bridge_geometry_msgs_Twist* _this = reinterpret_cast< RACS2Bridge_geometry_msgs_Twist* >(object);
  (void)_this;
}
void RACS2Bridge_geometry_msgs_Twist::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RACS2Bridge_geometry_msgs_Twist::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RACS2Bridge_geometry_msgs_Twist& RACS2Bridge_geometry_msgs_Twist::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RACS2Bridge_geometry_msgs_Twist_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base);
  return *internal_default_instance();
}


void RACS2Bridge_geometry_msgs_Twist::Clear() {
// @@protoc_insertion_point(message_clear_start:RACS2Bridge_geometry_msgs_Twist)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(linear_ != nullptr);
      linear_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(angular_ != nullptr);
      angular_->Clear();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RACS2Bridge_geometry_msgs_Twist::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // required .RACS2Bridge_geometry_msgs_Vector3 linear = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_linear(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // required .RACS2Bridge_geometry_msgs_Vector3 angular = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_angular(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RACS2Bridge_geometry_msgs_Twist::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RACS2Bridge_geometry_msgs_Twist)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required .RACS2Bridge_geometry_msgs_Vector3 linear = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::linear(this), target, stream);
  }

  // required .RACS2Bridge_geometry_msgs_Vector3 angular = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::angular(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RACS2Bridge_geometry_msgs_Twist)
  return target;
}

size_t RACS2Bridge_geometry_msgs_Twist::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:RACS2Bridge_geometry_msgs_Twist)
  size_t total_size = 0;

  if (_internal_has_linear()) {
    // required .RACS2Bridge_geometry_msgs_Vector3 linear = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *linear_);
  }

  if (_internal_has_angular()) {
    // required .RACS2Bridge_geometry_msgs_Vector3 angular = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *angular_);
  }

  return total_size;
}
size_t RACS2Bridge_geometry_msgs_Twist::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RACS2Bridge_geometry_msgs_Twist)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required .RACS2Bridge_geometry_msgs_Vector3 linear = 1;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *linear_);

    // required .RACS2Bridge_geometry_msgs_Vector3 angular = 2;
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *angular_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RACS2Bridge_geometry_msgs_Twist::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RACS2Bridge_geometry_msgs_Twist)
  GOOGLE_DCHECK_NE(&from, this);
  const RACS2Bridge_geometry_msgs_Twist* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RACS2Bridge_geometry_msgs_Twist>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RACS2Bridge_geometry_msgs_Twist)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RACS2Bridge_geometry_msgs_Twist)
    MergeFrom(*source);
  }
}

void RACS2Bridge_geometry_msgs_Twist::MergeFrom(const RACS2Bridge_geometry_msgs_Twist& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RACS2Bridge_geometry_msgs_Twist)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_mutable_linear()->::RACS2Bridge_geometry_msgs_Vector3::MergeFrom(from._internal_linear());
    }
    if (cached_has_bits & 0x00000002u) {
      _internal_mutable_angular()->::RACS2Bridge_geometry_msgs_Vector3::MergeFrom(from._internal_angular());
    }
  }
}

void RACS2Bridge_geometry_msgs_Twist::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RACS2Bridge_geometry_msgs_Twist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RACS2Bridge_geometry_msgs_Twist::CopyFrom(const RACS2Bridge_geometry_msgs_Twist& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RACS2Bridge_geometry_msgs_Twist)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RACS2Bridge_geometry_msgs_Twist::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  if (_internal_has_linear()) {
    if (!linear_->IsInitialized()) return false;
  }
  if (_internal_has_angular()) {
    if (!angular_->IsInitialized()) return false;
  }
  return true;
}

void RACS2Bridge_geometry_msgs_Twist::InternalSwap(RACS2Bridge_geometry_msgs_Twist* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(RACS2Bridge_geometry_msgs_Twist, angular_)
      + sizeof(RACS2Bridge_geometry_msgs_Twist::angular_)
      - PROTOBUF_FIELD_OFFSET(RACS2Bridge_geometry_msgs_Twist, linear_)>(
          reinterpret_cast<char*>(&linear_),
          reinterpret_cast<char*>(&other->linear_));
}

::PROTOBUF_NAMESPACE_ID::Metadata RACS2Bridge_geometry_msgs_Twist::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void RACS2Bridge_geometry_msgs::InitAsDefaultInstance() {
}
class RACS2Bridge_geometry_msgs::_Internal {
 public:
};

RACS2Bridge_geometry_msgs::RACS2Bridge_geometry_msgs(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  accel_with_covariance_data_(arena),
  accel_with_covariance_stamped_data_(arena),
  point_stamped_data_(arena),
  inertia_stamped_data_(arena),
  quaternion_stamped_data_(arena),
  transform_stamped_data_(arena),
  inertia_data_(arena),
  pose_with_covariance_data_(arena),
  twist_covariance_stamped_data_(arena),
  wrench_data_(arena),
  accel_data_(arena),
  pose_with_covariance_stamped_data_(arena),
  accele_stamped_data_(arena),
  transform_data_(arena),
  point_data_(arena),
  polygon_stamped_dta_(arena),
  pose_array_data_(arena),
  vector3_stamped_data_(arena),
  pose_stamped_data_(arena),
  polygon_data_(arena),
  queaternion_data_(arena),
  point32_data_(arena),
  twist_with_covariance_data_(arena),
  pose_data_(arena),
  twist_stamped_data_(arena),
  pose_2d_data_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:RACS2Bridge_geometry_msgs)
}
RACS2Bridge_geometry_msgs::RACS2Bridge_geometry_msgs(const RACS2Bridge_geometry_msgs& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      accel_with_covariance_data_(from.accel_with_covariance_data_),
      accel_with_covariance_stamped_data_(from.accel_with_covariance_stamped_data_),
      point_stamped_data_(from.point_stamped_data_),
      inertia_stamped_data_(from.inertia_stamped_data_),
      quaternion_stamped_data_(from.quaternion_stamped_data_),
      transform_stamped_data_(from.transform_stamped_data_),
      inertia_data_(from.inertia_data_),
      pose_with_covariance_data_(from.pose_with_covariance_data_),
      twist_covariance_stamped_data_(from.twist_covariance_stamped_data_),
      wrench_data_(from.wrench_data_),
      accel_data_(from.accel_data_),
      pose_with_covariance_stamped_data_(from.pose_with_covariance_stamped_data_),
      accele_stamped_data_(from.accele_stamped_data_),
      transform_data_(from.transform_data_),
      point_data_(from.point_data_),
      polygon_stamped_dta_(from.polygon_stamped_dta_),
      pose_array_data_(from.pose_array_data_),
      vector3_stamped_data_(from.vector3_stamped_data_),
      pose_stamped_data_(from.pose_stamped_data_),
      polygon_data_(from.polygon_data_),
      queaternion_data_(from.queaternion_data_),
      point32_data_(from.point32_data_),
      twist_with_covariance_data_(from.twist_with_covariance_data_),
      pose_data_(from.pose_data_),
      twist_stamped_data_(from.twist_stamped_data_),
      pose_2d_data_(from.pose_2d_data_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:RACS2Bridge_geometry_msgs)
}

void RACS2Bridge_geometry_msgs::SharedCtor() {
}

RACS2Bridge_geometry_msgs::~RACS2Bridge_geometry_msgs() {
  // @@protoc_insertion_point(destructor:RACS2Bridge_geometry_msgs)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void RACS2Bridge_geometry_msgs::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void RACS2Bridge_geometry_msgs::ArenaDtor(void* object) {
  RACS2Bridge_geometry_msgs* _this = reinterpret_cast< RACS2Bridge_geometry_msgs* >(object);
  (void)_this;
}
void RACS2Bridge_geometry_msgs::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void RACS2Bridge_geometry_msgs::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const RACS2Bridge_geometry_msgs& RACS2Bridge_geometry_msgs::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_RACS2Bridge_geometry_msgs_RACS2Bridge_5fgeometry_5fmsgs_2eproto.base);
  return *internal_default_instance();
}


void RACS2Bridge_geometry_msgs::Clear() {
// @@protoc_insertion_point(message_clear_start:RACS2Bridge_geometry_msgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  accel_with_covariance_data_.Clear();
  accel_with_covariance_stamped_data_.Clear();
  point_stamped_data_.Clear();
  inertia_stamped_data_.Clear();
  quaternion_stamped_data_.Clear();
  transform_stamped_data_.Clear();
  inertia_data_.Clear();
  pose_with_covariance_data_.Clear();
  twist_covariance_stamped_data_.Clear();
  wrench_data_.Clear();
  accel_data_.Clear();
  pose_with_covariance_stamped_data_.Clear();
  accele_stamped_data_.Clear();
  transform_data_.Clear();
  point_data_.Clear();
  polygon_stamped_dta_.Clear();
  pose_array_data_.Clear();
  vector3_stamped_data_.Clear();
  pose_stamped_data_.Clear();
  polygon_data_.Clear();
  queaternion_data_.Clear();
  point32_data_.Clear();
  twist_with_covariance_data_.Clear();
  pose_data_.Clear();
  twist_stamped_data_.Clear();
  pose_2d_data_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RACS2Bridge_geometry_msgs::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated float accel_with_covariance_data = 1 [packed = true];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_accel_with_covariance_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13) {
          _internal_add_accel_with_covariance_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float accel_with_covariance_stamped_data = 2 [packed = true];
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_accel_with_covariance_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 21) {
          _internal_add_accel_with_covariance_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float point_stamped_data = 3 [packed = true];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_point_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 29) {
          _internal_add_point_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float inertia_stamped_data = 4 [packed = true];
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_inertia_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37) {
          _internal_add_inertia_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float quaternion_stamped_data = 5 [packed = true];
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 42)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_quaternion_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45) {
          _internal_add_quaternion_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float transform_stamped_data = 6 [packed = true];
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_transform_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53) {
          _internal_add_transform_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float inertia_data = 7 [packed = true];
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_inertia_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 61) {
          _internal_add_inertia_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_with_covariance_data = 8 [packed = true];
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 66)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_with_covariance_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69) {
          _internal_add_pose_with_covariance_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float twist_covariance_stamped_data = 9 [packed = true];
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 74)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_twist_covariance_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 77) {
          _internal_add_twist_covariance_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float wrench_data = 10 [packed = true];
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 82)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_wrench_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 85) {
          _internal_add_wrench_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float accel_data = 11 [packed = true];
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 90)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_accel_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 93) {
          _internal_add_accel_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_with_covariance_stamped_data = 12 [packed = true];
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 98)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_with_covariance_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101) {
          _internal_add_pose_with_covariance_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float accele_stamped_data = 13 [packed = true];
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 106)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_accele_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 109) {
          _internal_add_accele_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float transform_data = 14 [packed = true];
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 114)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_transform_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 117) {
          _internal_add_transform_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float point_data = 15 [packed = true];
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 122)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_point_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 125) {
          _internal_add_point_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float polygon_stamped_dta = 16 [packed = true];
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 130)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_polygon_stamped_dta(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 133) {
          _internal_add_polygon_stamped_dta(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_array_data = 17 [packed = true];
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 138)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_array_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 141) {
          _internal_add_pose_array_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float vector3_stamped_data = 18 [packed = true];
      case 18:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 146)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_vector3_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 149) {
          _internal_add_vector3_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_stamped_data = 19 [packed = true];
      case 19:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 154)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 157) {
          _internal_add_pose_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float polygon_data = 20 [packed = true];
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 162)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_polygon_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 165) {
          _internal_add_polygon_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float queaternion_data = 21 [packed = true];
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 170)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_queaternion_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 173) {
          _internal_add_queaternion_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float point32_data = 22 [packed = true];
      case 22:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 178)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_point32_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 181) {
          _internal_add_point32_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float twist_with_covariance_data = 23 [packed = true];
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 186)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_twist_with_covariance_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 189) {
          _internal_add_twist_with_covariance_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_data = 24 [packed = true];
      case 24:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 194)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 197) {
          _internal_add_pose_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float twist_stamped_data = 25 [packed = true];
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 202)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_twist_stamped_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 205) {
          _internal_add_twist_stamped_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // repeated float pose_2d_data = 26 [packed = true];
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 210)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedFloatParser(_internal_mutable_pose_2d_data(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 213) {
          _internal_add_pose_2d_data(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* RACS2Bridge_geometry_msgs::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:RACS2Bridge_geometry_msgs)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated float accel_with_covariance_data = 1 [packed = true];
  if (this->_internal_accel_with_covariance_data_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_accel_with_covariance_data(), target);
  }

  // repeated float accel_with_covariance_stamped_data = 2 [packed = true];
  if (this->_internal_accel_with_covariance_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_accel_with_covariance_stamped_data(), target);
  }

  // repeated float point_stamped_data = 3 [packed = true];
  if (this->_internal_point_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(3, _internal_point_stamped_data(), target);
  }

  // repeated float inertia_stamped_data = 4 [packed = true];
  if (this->_internal_inertia_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(4, _internal_inertia_stamped_data(), target);
  }

  // repeated float quaternion_stamped_data = 5 [packed = true];
  if (this->_internal_quaternion_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(5, _internal_quaternion_stamped_data(), target);
  }

  // repeated float transform_stamped_data = 6 [packed = true];
  if (this->_internal_transform_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(6, _internal_transform_stamped_data(), target);
  }

  // repeated float inertia_data = 7 [packed = true];
  if (this->_internal_inertia_data_size() > 0) {
    target = stream->WriteFixedPacked(7, _internal_inertia_data(), target);
  }

  // repeated float pose_with_covariance_data = 8 [packed = true];
  if (this->_internal_pose_with_covariance_data_size() > 0) {
    target = stream->WriteFixedPacked(8, _internal_pose_with_covariance_data(), target);
  }

  // repeated float twist_covariance_stamped_data = 9 [packed = true];
  if (this->_internal_twist_covariance_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(9, _internal_twist_covariance_stamped_data(), target);
  }

  // repeated float wrench_data = 10 [packed = true];
  if (this->_internal_wrench_data_size() > 0) {
    target = stream->WriteFixedPacked(10, _internal_wrench_data(), target);
  }

  // repeated float accel_data = 11 [packed = true];
  if (this->_internal_accel_data_size() > 0) {
    target = stream->WriteFixedPacked(11, _internal_accel_data(), target);
  }

  // repeated float pose_with_covariance_stamped_data = 12 [packed = true];
  if (this->_internal_pose_with_covariance_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(12, _internal_pose_with_covariance_stamped_data(), target);
  }

  // repeated float accele_stamped_data = 13 [packed = true];
  if (this->_internal_accele_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(13, _internal_accele_stamped_data(), target);
  }

  // repeated float transform_data = 14 [packed = true];
  if (this->_internal_transform_data_size() > 0) {
    target = stream->WriteFixedPacked(14, _internal_transform_data(), target);
  }

  // repeated float point_data = 15 [packed = true];
  if (this->_internal_point_data_size() > 0) {
    target = stream->WriteFixedPacked(15, _internal_point_data(), target);
  }

  // repeated float polygon_stamped_dta = 16 [packed = true];
  if (this->_internal_polygon_stamped_dta_size() > 0) {
    target = stream->WriteFixedPacked(16, _internal_polygon_stamped_dta(), target);
  }

  // repeated float pose_array_data = 17 [packed = true];
  if (this->_internal_pose_array_data_size() > 0) {
    target = stream->WriteFixedPacked(17, _internal_pose_array_data(), target);
  }

  // repeated float vector3_stamped_data = 18 [packed = true];
  if (this->_internal_vector3_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(18, _internal_vector3_stamped_data(), target);
  }

  // repeated float pose_stamped_data = 19 [packed = true];
  if (this->_internal_pose_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(19, _internal_pose_stamped_data(), target);
  }

  // repeated float polygon_data = 20 [packed = true];
  if (this->_internal_polygon_data_size() > 0) {
    target = stream->WriteFixedPacked(20, _internal_polygon_data(), target);
  }

  // repeated float queaternion_data = 21 [packed = true];
  if (this->_internal_queaternion_data_size() > 0) {
    target = stream->WriteFixedPacked(21, _internal_queaternion_data(), target);
  }

  // repeated float point32_data = 22 [packed = true];
  if (this->_internal_point32_data_size() > 0) {
    target = stream->WriteFixedPacked(22, _internal_point32_data(), target);
  }

  // repeated float twist_with_covariance_data = 23 [packed = true];
  if (this->_internal_twist_with_covariance_data_size() > 0) {
    target = stream->WriteFixedPacked(23, _internal_twist_with_covariance_data(), target);
  }

  // repeated float pose_data = 24 [packed = true];
  if (this->_internal_pose_data_size() > 0) {
    target = stream->WriteFixedPacked(24, _internal_pose_data(), target);
  }

  // repeated float twist_stamped_data = 25 [packed = true];
  if (this->_internal_twist_stamped_data_size() > 0) {
    target = stream->WriteFixedPacked(25, _internal_twist_stamped_data(), target);
  }

  // repeated float pose_2d_data = 26 [packed = true];
  if (this->_internal_pose_2d_data_size() > 0) {
    target = stream->WriteFixedPacked(26, _internal_pose_2d_data(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RACS2Bridge_geometry_msgs)
  return target;
}

size_t RACS2Bridge_geometry_msgs::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RACS2Bridge_geometry_msgs)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated float accel_with_covariance_data = 1 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_accel_with_covariance_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _accel_with_covariance_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float accel_with_covariance_stamped_data = 2 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_accel_with_covariance_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _accel_with_covariance_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float point_stamped_data = 3 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_point_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _point_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float inertia_stamped_data = 4 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_inertia_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _inertia_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float quaternion_stamped_data = 5 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_quaternion_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _quaternion_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float transform_stamped_data = 6 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_transform_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _transform_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float inertia_data = 7 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_inertia_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _inertia_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_with_covariance_data = 8 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_with_covariance_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_with_covariance_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float twist_covariance_stamped_data = 9 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_twist_covariance_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _twist_covariance_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float wrench_data = 10 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_wrench_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _wrench_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float accel_data = 11 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_accel_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _accel_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_with_covariance_stamped_data = 12 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_with_covariance_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_with_covariance_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float accele_stamped_data = 13 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_accele_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _accele_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float transform_data = 14 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_transform_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _transform_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float point_data = 15 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_point_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _point_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float polygon_stamped_dta = 16 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_polygon_stamped_dta_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _polygon_stamped_dta_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_array_data = 17 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_array_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_array_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float vector3_stamped_data = 18 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_vector3_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _vector3_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_stamped_data = 19 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float polygon_data = 20 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_polygon_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _polygon_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float queaternion_data = 21 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_queaternion_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _queaternion_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float point32_data = 22 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_point32_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _point32_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float twist_with_covariance_data = 23 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_twist_with_covariance_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _twist_with_covariance_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_data = 24 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float twist_stamped_data = 25 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_twist_stamped_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _twist_stamped_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated float pose_2d_data = 26 [packed = true];
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_pose_2d_data_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _pose_2d_data_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RACS2Bridge_geometry_msgs::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RACS2Bridge_geometry_msgs)
  GOOGLE_DCHECK_NE(&from, this);
  const RACS2Bridge_geometry_msgs* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<RACS2Bridge_geometry_msgs>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RACS2Bridge_geometry_msgs)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RACS2Bridge_geometry_msgs)
    MergeFrom(*source);
  }
}

void RACS2Bridge_geometry_msgs::MergeFrom(const RACS2Bridge_geometry_msgs& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RACS2Bridge_geometry_msgs)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  accel_with_covariance_data_.MergeFrom(from.accel_with_covariance_data_);
  accel_with_covariance_stamped_data_.MergeFrom(from.accel_with_covariance_stamped_data_);
  point_stamped_data_.MergeFrom(from.point_stamped_data_);
  inertia_stamped_data_.MergeFrom(from.inertia_stamped_data_);
  quaternion_stamped_data_.MergeFrom(from.quaternion_stamped_data_);
  transform_stamped_data_.MergeFrom(from.transform_stamped_data_);
  inertia_data_.MergeFrom(from.inertia_data_);
  pose_with_covariance_data_.MergeFrom(from.pose_with_covariance_data_);
  twist_covariance_stamped_data_.MergeFrom(from.twist_covariance_stamped_data_);
  wrench_data_.MergeFrom(from.wrench_data_);
  accel_data_.MergeFrom(from.accel_data_);
  pose_with_covariance_stamped_data_.MergeFrom(from.pose_with_covariance_stamped_data_);
  accele_stamped_data_.MergeFrom(from.accele_stamped_data_);
  transform_data_.MergeFrom(from.transform_data_);
  point_data_.MergeFrom(from.point_data_);
  polygon_stamped_dta_.MergeFrom(from.polygon_stamped_dta_);
  pose_array_data_.MergeFrom(from.pose_array_data_);
  vector3_stamped_data_.MergeFrom(from.vector3_stamped_data_);
  pose_stamped_data_.MergeFrom(from.pose_stamped_data_);
  polygon_data_.MergeFrom(from.polygon_data_);
  queaternion_data_.MergeFrom(from.queaternion_data_);
  point32_data_.MergeFrom(from.point32_data_);
  twist_with_covariance_data_.MergeFrom(from.twist_with_covariance_data_);
  pose_data_.MergeFrom(from.pose_data_);
  twist_stamped_data_.MergeFrom(from.twist_stamped_data_);
  pose_2d_data_.MergeFrom(from.pose_2d_data_);
}

void RACS2Bridge_geometry_msgs::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RACS2Bridge_geometry_msgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RACS2Bridge_geometry_msgs::CopyFrom(const RACS2Bridge_geometry_msgs& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RACS2Bridge_geometry_msgs)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RACS2Bridge_geometry_msgs::IsInitialized() const {
  return true;
}

void RACS2Bridge_geometry_msgs::InternalSwap(RACS2Bridge_geometry_msgs* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  accel_with_covariance_data_.InternalSwap(&other->accel_with_covariance_data_);
  accel_with_covariance_stamped_data_.InternalSwap(&other->accel_with_covariance_stamped_data_);
  point_stamped_data_.InternalSwap(&other->point_stamped_data_);
  inertia_stamped_data_.InternalSwap(&other->inertia_stamped_data_);
  quaternion_stamped_data_.InternalSwap(&other->quaternion_stamped_data_);
  transform_stamped_data_.InternalSwap(&other->transform_stamped_data_);
  inertia_data_.InternalSwap(&other->inertia_data_);
  pose_with_covariance_data_.InternalSwap(&other->pose_with_covariance_data_);
  twist_covariance_stamped_data_.InternalSwap(&other->twist_covariance_stamped_data_);
  wrench_data_.InternalSwap(&other->wrench_data_);
  accel_data_.InternalSwap(&other->accel_data_);
  pose_with_covariance_stamped_data_.InternalSwap(&other->pose_with_covariance_stamped_data_);
  accele_stamped_data_.InternalSwap(&other->accele_stamped_data_);
  transform_data_.InternalSwap(&other->transform_data_);
  point_data_.InternalSwap(&other->point_data_);
  polygon_stamped_dta_.InternalSwap(&other->polygon_stamped_dta_);
  pose_array_data_.InternalSwap(&other->pose_array_data_);
  vector3_stamped_data_.InternalSwap(&other->vector3_stamped_data_);
  pose_stamped_data_.InternalSwap(&other->pose_stamped_data_);
  polygon_data_.InternalSwap(&other->polygon_data_);
  queaternion_data_.InternalSwap(&other->queaternion_data_);
  point32_data_.InternalSwap(&other->point32_data_);
  twist_with_covariance_data_.InternalSwap(&other->twist_with_covariance_data_);
  pose_data_.InternalSwap(&other->pose_data_);
  twist_stamped_data_.InternalSwap(&other->twist_stamped_data_);
  pose_2d_data_.InternalSwap(&other->pose_2d_data_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RACS2Bridge_geometry_msgs::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::RACS2Bridge_geometry_msgs_Vector3* Arena::CreateMaybeMessage< ::RACS2Bridge_geometry_msgs_Vector3 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RACS2Bridge_geometry_msgs_Vector3 >(arena);
}
template<> PROTOBUF_NOINLINE ::RACS2Bridge_geometry_msgs_Twist* Arena::CreateMaybeMessage< ::RACS2Bridge_geometry_msgs_Twist >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RACS2Bridge_geometry_msgs_Twist >(arena);
}
template<> PROTOBUF_NOINLINE ::RACS2Bridge_geometry_msgs* Arena::CreateMaybeMessage< ::RACS2Bridge_geometry_msgs >(Arena* arena) {
  return Arena::CreateMessageInternal< ::RACS2Bridge_geometry_msgs >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
